### ISSUE TITLE
closes roblox

### ISSUE THREAD

**Issue by mxg1129** [Bonzai-Dev/Bloxburg-cash-farm#1]
anytime i launch it it closes my roblox could this be becaus i missplace the cursor or a setting that isnt right and are there any fixes for it

**Comment by Bonzai-Dev** [comment]
Yeah, it may be because you misplaced the positions for the cursor. You'll have to find a way to get them.

**Comment by mxg1129** [comment]
where could i change the possition of the cursor bc in the menu i cant find it it only lets me change the possition of the screenshots and not from the corsor

**Comment by Bonzai-Dev** [comment]
Actually, nevermind what i said... but did you set up the settings correctly? You will have to take a screenshot for all the items and tweak the detection thresholds manually

**Comment by mxg1129** [comment]
im sorry to ask but how do i do that exactly im not that good with computers

**Comment by Bonzai-Dev** [comment]
So ill explain a bit how the program works. It basically just detects if an image that you have specified is on screen. Thats called image detection. Lets say that we have a fry on the screen and we want to click on it. The program will check on the screen for anything that matches the fry image that you specified and will click on that image on the screen. Now the ai will sometimes be mistaken so you have to tweak the detection thresholds to tell the ai to be either more certain or less certain of the image.

**Comment by Bonzai-Dev** [comment]
So with that being said, you will have to take screenshots yourself and tweak the thresholds manually. It took me some time to tweak it so that everything is perfect. And In case you don't know what to screenshot, check the img folder located in the program's folder and copy what I did. And if you also didn't realise, you will need to replace the screenshots I took with yours.

**Comment by mxg1129** [comment]
yeah that i get but how do i change the treshholds bc i have checked the picctures and they al match

**Comment by Bonzai-Dev** [comment]
It's in the control panel. You'll see a title written "Items Detection Threshold". Under that are all the thresholds that you need to tweak.

**Comment by mxg1129** [comment]
alr thank you
